# Generated by Django 2.2.10 on 2020-02-23 22:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0003_spectralwindow_observation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='observation',
            name='mosaic',
        ),
        migrations.AddField(
            model_name='trace',
            name='observation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='common.Observation'),
        ),
    ]
