# Generated by Django 2.2.10 on 2020-02-27 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0004_auto_20200223_2222'),
    ]

    operations = [
        migrations.AddField(
            model_name='trace',
            name='fov',
            field=models.FloatField(default=0),
        ),
    ]
