# Generated by Django 2.2.10 on 2020-02-27 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0005_trace_fov'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trace',
            name='fov',
            field=models.FloatField(),
        ),
    ]
