# Generated by Django 2.2.10 on 2020-02-27 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0006_auto_20200227_1114'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trace',
            old_name='fov',
            new_name='fovaaa',
        ),
    ]
