# Generated by Django 2.2.10 on 2020-02-27 11:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0007_auto_20200227_1117'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trace',
            old_name='fovaaa',
            new_name='fov',
        ),
    ]
