# Generated by Django 2.2.10 on 2020-03-12 10:33

from django.db import migrations


class Migration(migrations.Migration):
    atomic = False
    dependencies = [
        ('common', '0012_auto_20200312_1027'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Antenna',
            new_name='Array',
        ),
        migrations.RenameField(
            model_name='observation',
            old_name='array',
            new_name='arrays',
        ),
    ]
