# Generated by Django 3.0.2 on 2020-02-20 14:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SpectralWindow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.FloatField()),
                ('end', models.FloatField()),
                ('resolution', models.FloatField()),
                ('sensitivity_10kms', models.FloatField()),
                ('sensitivity_native', models.FloatField()),
                ('pol_product', models.CharField(choices=[('XX YY', 'XX YY'), ('XX', 'XX'), ('XX XY YX YY', 'XX XY YX YY')], max_length=11)),
            ],
        ),
        migrations.CreateModel(
            name='Trace',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ra', models.FloatField()),
                ('dec', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Observation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_code', models.CharField(max_length=14)),
                ('source_name', models.CharField(max_length=50)),
                ('ra', models.FloatField()),
                ('dec', models.FloatField()),
                ('gal_longitude', models.FloatField()),
                ('gal_latitude', models.FloatField()),
                ('band', models.IntegerField()),
                ('spatial_resolution', models.FloatField()),
                ('frequency_resolution', models.FloatField()),
                ('array', models.IntegerField(choices=[(7, '7m'), (12, '12m')])),
                ('integration_time', models.FloatField()),
                ('release_date', models.DateField()),
                ('velocity_resolution', models.FloatField()),
                ('pol_product', models.CharField(choices=[('XX YY', 'XX YY'), ('XX', 'XX'), ('XX XY YX YY', 'XX XY YX YY')], max_length=11)),
                ('observation_date', models.DateTimeField()),
                ('pi_name', models.CharField(max_length=50)),
                ('sb_name', models.CharField(max_length=50)),
                ('proposal_authors', models.CharField(max_length=400)),
                ('line_sensitivity', models.FloatField()),
                ('continuum_sensitivity', models.FloatField()),
                ('pwv', models.FloatField()),
                ('group_ous_id', models.CharField(max_length=50)),
                ('member_ous_id', models.CharField(max_length=50)),
                ('asdm_uid', models.CharField(max_length=50)),
                ('project_title', models.CharField(max_length=800)),
                ('project_type', models.CharField(choices=[('CAL', 'CAL'), ('L', 'L'), ('S', 'S'), ('SIM', 'SIM'), ('SV', 'SV'), ('T', 'T'), ('V', 'V')], max_length=3)),
                ('scan_intent', models.CharField(max_length=30)),
                ('field_of_view', models.FloatField()),
                ('largest_angular_scale', models.FloatField()),
                ('qa2_status', models.CharField(max_length=1)),
                ('count', models.FloatField()),
                ('science_keywords', models.CharField(max_length=50)),
                ('scientific_cat', models.CharField(max_length=100)),
                ('asa_project_code', models.CharField(max_length=14)),
                ('freq_support', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.SpectralWindow')),
                ('mosaic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.Trace')),
            ],
        ),
    ]
