# Generated by Django 2.2.10 on 2020-02-23 22:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='observation',
            name='freq_support',
        ),
    ]
