# Generated by Django 2.2.10 on 2020-02-23 22:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_remove_observation_freq_support'),
    ]

    operations = [
        migrations.AddField(
            model_name='spectralwindow',
            name='observation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='common.Observation'),
        ),
    ]
