# Generated by Django 2.2.10 on 2020-02-27 13:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0008_auto_20200227_1118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spectralwindow',
            name='observation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='spec_windows', to='common.Observation'),
        ),
        migrations.AlterField(
            model_name='trace',
            name='observation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='traces', to='common.Observation'),
        ),
    ]
