# Generated by Django 2.2.10 on 2020-03-12 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0011_antenna'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='observation',
            name='array',
        ),
        migrations.AddField(
            model_name='observation',
            name='array',
            field=models.ManyToManyField(to='common.Antenna'),
        ),
    ]
