# Generated by Django 2.2.10 on 2020-03-12 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0013_auto_20200312_1033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='array',
            name='designation',
            field=models.CharField(choices=[('12', '12m'), ('7', '7m'), ('TP', 'Total power')], max_length=2),
        ),
    ]
