# Generated by Django 2.2.10 on 2020-03-12 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0014_auto_20200312_1042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='observation',
            name='release_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
