# Generated by Django 2.2.10 on 2020-05-30 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0015_auto_20200312_1450'),
    ]

    operations = [
        migrations.AddField(
            model_name='band',
            name='end',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='band',
            name='start',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
