# Generated by Django 2.2.10 on 2020-09-18 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0016_auto_20200530_1927'),
    ]

    operations = [
        migrations.AddField(
            model_name='observation',
            name='mosaic',
            field=models.BooleanField(default=False),
        ),
    ]
