# Generated by Django 2.2.10 on 2021-01-10 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0020_auto_20210110_1603'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EmissionLine',
        ),
    ]
