# Generated by Django 2.2.10 on 2021-01-23 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0022_emissionline'),
    ]

    operations = [
        migrations.AddField(
            model_name='emissionline',
            name='line_id',
            field=models.CharField(default='a', max_length=35),
            preserve_default=False,
        ),
    ]
