# Generated by Django 3.1.7 on 2021-05-01 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0023_emissionline_line_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='emissionline',
            name='image_file',
            field=models.CharField(max_length=25, null=True),
        ),
    ]
