# Generated by Django 3.1.7 on 2021-05-18 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0024_emissionline_image_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='observation',
            name='footprint',
            field=models.CharField(default='', max_length=10000),
            preserve_default=False,
        ),
    ]
