# Generated by Django 3.1.7 on 2021-05-19 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0025_observation_footprint'),
    ]

    operations = [
        migrations.AddField(
            model_name='observation',
            name='total_area',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
