# Generated by Django 3.1.7 on 2021-05-26 20:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0026_observation_total_area'),
        ('common', '0025_observation_total_area'),
    ]

    operations = [
    ]
