# Generated by Django 3.1.7 on 2021-04-17 15:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cluster_0',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ra', models.FloatField()),
                ('dec', models.FloatField()),
                ('area_total', models.FloatField()),
                ('area_overlap', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Cluster_1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ra', models.FloatField()),
                ('dec', models.FloatField()),
                ('area_total', models.FloatField()),
                ('area_overlap', models.FloatField()),
                ('parent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='sky_map.cluster_0')),
            ],
        ),
    ]
