# Generated by Django 3.1.7 on 2021-04-18 16:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0023_emissionline_line_id'),
        ('sky_map', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Overlap',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area_num', models.FloatField()),
                ('obs1', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='obs_1', to='common.observation')),
                ('obs2', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='obs_2', to='common.observation')),
            ],
        ),
    ]
