# Generated by Django 3.1.7 on 2021-05-26 20:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0027_merge_20210526_2010'),
        ('sky_map', '0002_overlap'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cluster_1',
            name='parent',
        ),
        migrations.AddField(
            model_name='cluster_0',
            name='parent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='sky_map.cluster_1'),
        ),
        migrations.CreateModel(
            name='Obs_Link',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('obs', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='obs', to='common.observation')),
                ('parent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='sky_map.cluster_0')),
            ],
        ),
    ]
