# Generated by Django 3.1.7 on 2021-05-28 20:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sky_map', '0003_auto_20210526_2010'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cluster',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.IntegerField()),
                ('ra', models.FloatField()),
                ('dec', models.FloatField()),
                ('area_total', models.FloatField()),
                ('area_overlap', models.FloatField()),
                ('parent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='sky_map.cluster')),
            ],
        ),
        migrations.RemoveField(
            model_name='cluster_0',
            name='parent',
        ),
        migrations.DeleteModel(
            name='Cluster_1',
        ),
        migrations.AlterField(
            model_name='obs_link',
            name='parent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cluster_obs', to='sky_map.cluster'),
        ),
        migrations.DeleteModel(
            name='Cluster_0',
        ),
    ]
