# Generated by Django 3.1.7 on 2021-05-28 20:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0027_merge_20210526_2010'),
        ('sky_map', '0004_auto_20210528_2017'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Obs_Link',
            new_name='ObsRef',
        ),
    ]
