# Generated by Django 3.1.7 on 2021-06-05 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sky_map', '0007_cluster_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cluster',
            name='count',
            field=models.IntegerField(),
        ),
    ]
